models:
  MAIN_SNOMEDCT-AU_AUAMT:
    modelType: AMT
    moduleId: 32506021000036107
    preferredLanguageRefsets:
      - 32570271000036106
      - 900000000000509007
    baseMedicationSchema: classpath:AMT/base-medication-schema.json
    baseMedicationUiSchema: classpath:AMT/base-medication-ui-schema.json
    baseDeviceSchema: classpath:AMT/base-device-schema.json
    baseDeviceUiSchema: classpath:AMT/base-device-ui-schema.json
    baseBulkBrandSchema: classpath:AMT/base-bulk-brand-schema.json
    baseBulkBrandUiSchema: classpath:AMT/base-bulk-brand-ui-schema.json
    baseBulkPackSchema: classpath:AMT/base-bulk-pack-schema.json
    baseBulkPackUiSchema: classpath:AMT/base-bulk-pack-ui-schema.json
    subpackFromPackageEcl: "((<id>.999000011000168107) or (<id>.999000111000168106))"
    medicationPackageDataExtractionEcl: "(<id> or (<id>.999000011000168107) or (<id>.774160008) or (<id>.999000011000168107.774160008) or ((>>((<id>.774160008) or (<id>.999000011000168107.774160008))) and (^929360071000036103))) and <373873005"
    medicationProductDataExtractionEcl: "(<id> or (>> <id> and ^929360071000036103)) and <373873005"
    devicePackageDataExtractionEcl: "(<id> or (<id>.999000111000168106) or (<id>.999000081000168101) or (<id>.999000111000168106.999000081000168101) or ((>>((<id>.999000081000168101) or (<id>.999000111000168106.999000081000168101))) and (^929360071000036103 or ^929360061000036106))) and < 260787004"
    deviceProductDataExtractionEcl: "(<id> or (>> <id> and (^929360071000036103 or ^929360061000036106))) and < 260787004"
    levels:
      - name: Product
        displayLabel: MP
        displayName: Product
        modelLevelType: MEDICINAL_PRODUCT
        medicineSemanticTag: medicinal product
        drugDeviceSemanticTag: medicinal product
        deviceSemanticTag: physical object
        referenceSetIdentifier: 929360061000036106
        productModelEcl: "((> <id>) and ^ 929360061000036106) minus >((> <id>) and ^ 929360061000036106)"
      - name: Generic Product
        displayLabel: MPUU
        modelLevelType: CLINICAL_DRUG
        medicineSemanticTag: clinical drug
        drugDeviceSemanticTag: product
        deviceSemanticTag: physical object
        referenceSetIdentifier: 929360071000036103
        productModelEcl: "((> <id>) and ^ 929360071000036103) minus >((> <id>) and ^ 929360071000036103)"
      - name: Branded Product
        displayLabel: TPUU
        modelLevelType: REAL_CLINICAL_DRUG
        medicineSemanticTag: branded clinical drug
        deviceSemanticTag: branded physical object
        drugDeviceSemanticTag: branded product
        referenceSetIdentifier: 929360031000036100
        productModelEcl: "(>> ((<id>.774160008) or (<id>.999000081000168101))) and (^ 929360031000036100)"
      - name: Generic Pack
        displayLabel: MPP
        modelLevelType: PACKAGED_CLINICAL_DRUG
        medicineSemanticTag: clinical drug package
        deviceSemanticTag: physical object package
        drugDeviceSemanticTag: product package
        referenceSetIdentifier: 929360081000036101
        productModelEcl: "((> <id>) and ^ 929360081000036101) minus >((> <id>) and ^ 929360081000036101)"
      - name: Branded Pack
        displayLabel: TPP
        modelLevelType: REAL_PACKAGED_CLINICAL_DRUG
        medicineSemanticTag: branded clinical drug package
        deviceSemanticTag: branded physical object package
        drugDeviceSemanticTag: branded product package
        referenceSetIdentifier: 929360041000036105
        productModelEcl: "(> <id>) and ^ 929360041000036105"
      - name: Branded Container
        displayLabel: CTPP
        modelLevelType: REAL_CONTAINERIZED_PACKAGED_CLINICAL_DRUG
        medicineSemanticTag: containerized branded clinical drug package
        deviceSemanticTag: containerized branded physical object package
        drugDeviceSemanticTag: containerized branded product package
        referenceSetIdentifier: 929360051000036108
      - name: Brand Name
        displayLabel: TP
        modelLevelType: PRODUCT_NAME
        medicineSemanticTag: product name
        deviceSemanticTag: product name
        drugDeviceSemanticTag: product name
        referenceSetIdentifier: 929360021000036102
        productModelEcl: ">> <id>.774158006"
    mappings:
      - name: artgid
        title: ARTGID
        description: Australian Register of Therapeutic Goods Identifier
        identifier: 11000168105
        level: PACKAGE
        dataType: STRING
        valueRegexValidation: \d{3,8}
        modelLevels: REAL_CONTAINERIZED_PACKAGED_CLINICAL_DRUG
        mandatory: false
        multiValued: true
        defaultMappingType: RELATED
        mappingTypes:
          - RELATED
    referenceSets:
    nonDefiningProperties:
  MAIN_SNOMEDCT-IE:
    modelType: NMPC
    moduleId: 1601000220105
    preferredLanguageRefsets:
      - 21000220103
      - 900000000000509007
    baseMedicationSchema: classpath:NMPC/base-medication-schema.json
    baseMedicationUiSchema: classpath:NMPC/base-medication-ui-schema.json
    baseDeviceSchema: classpath:NMPC/base-device-schema.json
    baseDeviceUiSchema: classpath:NMPC/base-device-ui-schema.json
    baseBulkBrandSchema: classpath:NMPC/base-bulk-brand-schema.json
    baseBulkBrandUiSchema: classpath:NMPC/base-bulk-brand-ui-schema.json
    baseBulkPackSchema: classpath:NMPC/base-bulk-pack-schema.json
    baseBulkPackUiSchema: classpath:NMPC/base-bulk-pack-ui-schema.json
    medicationPackageDataExtractionEcl: "(<id> or >>(>><id>.774160008)) and <373873005"
    medicationProductDataExtractionEcl: "(<id> or (>> <id> and ^660371000220109)) and <373873005"
    devicePackageDataExtractionEcl: "(<id> or (<id>.999000111000168106) or (<id>.999000081000168101) or (<id>.999000111000168106.999000081000168101) or ((>>((<id>.999000081000168101) or (<id>.999000111000168106.999000081000168101))) and (^929360071000036103 or ^929360061000036106))) and < 260787004"
    deviceProductDataExtractionEcl: "(<id> or (>> <id> and (^929360071000036103 or ^929360061000036106))) and < 260787004"
    trimWholeNumbers: true
    levels:
      - name: Virtual Therapeutic Moiety
        displayLabel: MP
        modelLevelType: MEDICINAL_PRODUCT_ONLY
        medicineSemanticTag: medicinal product
        deviceSemanticTag: physical object
        drugDeviceSemanticTag: medicinal product
        referenceSetIdentifier: 660351000220100
        productModelEcl: "((> <id>) and ^ 660351000220100) minus >((> <id>) and ^ 660351000220100)"
      - name: Virtual Medicinal Product
        displayLabel: MPUU
        modelLevelType: CLINICAL_DRUG
        medicineSemanticTag: clinical drug
        deviceSemanticTag: physical object
        drugDeviceSemanticTag: clinical drug
        referenceSetIdentifier: 660371000220109
        productModelEcl: "((> <id>) and ^ 660371000220109) minus >((> <id>) and ^ 660371000220109)"
      - name: Actual Medicinal Product
        displayLabel: TPUU
        modelLevelType: REAL_CLINICAL_DRUG
        medicineSemanticTag: real clinical drug
        deviceSemanticTag: branded physical object
        drugDeviceSemanticTag: real clinical drug
        referenceSetIdentifier: 660381000220107
        productModelEcl: "(>> (<id>.774160008)) and (^ 660381000220107)"
      - name: Virtual Medicinal Product Pack
        displayLabel: MPP
        modelLevelType: PACKAGED_CLINICAL_DRUG
        medicineSemanticTag: clinical drug package
        deviceSemanticTag: physical object package
        drugDeviceSemanticTag: clinical drug package
        referenceSetIdentifier: 660391000220105
        productModelEcl: "((> <id>) and ^ 660391000220105) minus >((> <id>) and ^ 660391000220105)"
      - name: Actual Medicinal Product Pack
        displayLabel: TPP
        modelLevelType: REAL_PACKAGED_CLINICAL_DRUG
        medicineSemanticTag: real clinical drug package
        deviceSemanticTag: branded physical object package
        drugDeviceSemanticTag: real clinical drug package
        referenceSetIdentifier: 660401000220107
      - name: Actual Therapeutic Moiety
        displayLabel: TP
        modelLevelType: REAL_MEDICINAL_PRODUCT
        medicineSemanticTag: real medicinal product
        deviceSemanticTag: branded physical object
        drugDeviceSemanticTag: real medicinal product
        referenceSetIdentifier: 660361000220103
        productModelEcl: "> <id> :774159003=*"
    mappings:
      - name: pan
        title: Product authorisation number
        description: HPRA or EMA product authorisation number
        identifier: 11000168105
        level: PRODUCT
        dataType: STRING
        valueRegexValidation: (PA\d{4,8}(\/\d{1,2})?(\/\d{1,2})?)|(EU\/\d{1,5}\/\d{1,5}\/\d{1,5})
        modelLevels: REAL_CONTAINERIZED_PACKAGED_CLINICAL_DRUG
        mandatory: false
        multiValued: true
        defaultMappingType: RELATED
        mappingTypes:
          - RELATED
      - name: pan
        title: Product authorisation number
        description: HPRA or EMA product authorisation number
        identifier: 11000168105
        level: PACKAGE
        dataType: STRING
        valueRegexValidation: (PA\d{4,8}(\/\d{1,2})?(\/\d{1,2})?)|(EU\/\d{1,5}\/\d{1,5}\/\d{1,5})
        modelLevels: REAL_CONTAINERIZED_PACKAGED_CLINICAL_DRUG
        mandatory: false
        multiValued: true
        defaultMappingType: RELATED
        mappingTypes:
          - RELATED
      - name: ean
        title: EAN
        identifier: 410607006
        level: PACKAGE
        dataType: UNSIGNED_INTEGER
        valueRegexValidation: \d{13}
        modelLevels: REAL_CONTAINERIZED_PACKAGED_CLINICAL_DRUG
        mandatory: false
        multiValued: true
        defaultMappingType: RELATED
        mappingTypes:
          - RELATED
      - name: gtin
        title: GTIN
        identifier: 71388002
        level: PACKAGE
        dataType: UNSIGNED_INTEGER
        valueRegexValidation: \d{8,14}
        modelLevels: REAL_CONTAINERIZED_PACKAGED_CLINICAL_DRUG
        mandatory: false
        multiValued: true
        defaultMappingType: RELATED
        mappingTypes:
          - RELATED
      - name: atc
        title: ATC level 5 code
        identifier: 84676004
        level: PACKAGE
        dataType: STRING,
        valueRegexValidation: ^.+$
        valueSetReference: http://www.whocc.no/atc/vs
        modelLevels: REAL_CONTAINERIZED_PACKAGED_CLINICAL_DRUG
        mandatory: false
        multiValued: true
        defaultMappingType: RELATED
        mappingTypes:
          - RELATED
      - name: pcrs
        title: GMS Reimbursable Number
        identifier: 105590001
        level: PACKAGE
        dataType: STRING,
        valueRegexValidation: ^.+$
        valueSetReference: https://nmpc.hse.ie/PCRS/vs
        modelLevels: REAL_CONTAINERIZED_PACKAGED_CLINICAL_DRUG
        mandatory: false
        multiValued: false
        defaultMappingType: RELATED
        mappingTypes:
          - RELATED
    referenceSets:
      - name: blackTriangle
        title: Black Triangle
        description: Medicines on the Black Triangle Scheme
        identifier: 419036000
        level: PRODUCT
        modelLevels: REAL_CONTAINERIZED_PACKAGED_CLINICAL_DRUG
      - name: combinationOnly
        title: Combination pack only
        description: Combination pack only
        identifier: 431134006
        level: PACKAGE
        modelLevels: REAL_CONTAINERIZED_PACKAGED_CLINICAL_DRUG
      - name: parallelImport
        title: Parallel import
        description: Parallel import
        identifier: 433741003
        level: PRODUCT
        modelLevels: REAL_CONTAINERIZED_PACKAGED_CLINICAL_DRUG
      - name: vmpNonPrescribable
        title: Non-prescribable VMP
        description: Non-prescribable VMP
        identifier: 1514151000168100
        level: PRODUCT
        modelLevels: REAL_CONTAINERIZED_PACKAGED_CLINICAL_DRUG
    nonDefiningProperties:
      - name: supplier
        title: Supplier
        description: Supplier
        identifier: 774159003
        level: PRODUCT
        dataType: CONCEPT
        eclBinding: <774164004
        modelLevels: REAL_CLINICAL_DRUG
        mandatory: false
        multiValued: true
      - name: licencedRoute
        title: Licenced Route
        description: Licenced Route of Administration
        identifier: 243637007
        level: PRODUCT
        dataType: CONCEPT
        eclBinding: <284009009
        modelLevels: REAL_CLINICAL_DRUG
        mandatory: false
        multiValued: true
      - name: pil
        title: Product information leaflet
        description: Product information leaflet
        identifier: 26366004
        level: PRODUCT
        dataType: URI
        valueRegexValidation: http(s)?://.+\.(pdf|html)
        modelLevels: REAL_CLINICAL_DRUG
        mandatory: false
        multiValued: true
      - name: smpc
        title: SmPC
        description: SmPC
        identifier: 243642004
        level: PRODUCT
        dataType: URI
        valueRegexValidation: http(s)?://.+\.(pdf|html)
        modelLevels: REAL_CLINICAL_DRUG
        mandatory: false
        multiValued: true
      - name: pil
        title: Product information leaflet
        description: Product information leaflet
        identifier: 243638002
        level: PACKAGE
        dataType: URI
        valueRegexValidation: http(s)?://.+\.(pdf|html)
        modelLevels: REAL_CLINICAL_DRUG
        mandatory: false
        multiValued: true
      - name: smpc
        title: SmPC
        description: SmPC
        identifier: 1445111000168100
        level: PACKAGE
        dataType: URI
        valueRegexValidation: http(s)?://.+\.(pdf|html)
        modelLevels: REAL_CLINICAL_DRUG
        mandatory: false
        multiValued: true