name: Check Changelog
on:
  pull_request:
    types: [ assigned, opened, synchronize, reopened, labeled, unlabeled ]
    branches:
      - main
jobs:
  check-changelog:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check if files have changed
        run: |
          FILES_CHANGED=$(git diff --name-only origin/main...HEAD | grep -E 'CHANGELOG\.md' -c)
          if [ "$FILES_CHANGED" != "1" ]; then echo "Remember to update CHANGELOG.md"; exit 1; fi;